### PR TITLE
Add discord reporting funtionality

### PR DESCRIPTION
**Pull request by jhaugh0**
Adds an option to options.py to configure a discord webhook, and adds a runtime switch for enabling reporting to it

### CODE REVIEW

**Comment by jjjchens235** [comment]
On a cursory glance, this looks good. A few things:
1. Please clean up your commit history
2. Please set a default discord argument , i.e False in options.py

**Comment by jhaugh0** [comment]
I forgot making changes via the online editor makes a new commit for everything..

Am I missing something for the default? From my testing it's defaulting to false unless called, and I'm not seeing anywhere else to manually specify that

**Comment by jjjchens235** [comment]
Thanks for rebasing.

Ok if the default looks good that's fine. I haven't pulled the code in yet, will try to get to it today.

**Comment by jjjchens235** [comment]
Ok so I'm trying to set-up this up myself and not 100% how to proceed.

I created a 
- new server
- a new webhook for the server called 'Captain_Hook'

My guess is that I'm supposed to run `python setup.py -d Captain_Hook`.
Then I ran `python BingRewards.py`

There are two issues here:
1. `discord_webhook=False` yet the discord code block was still called
2. I got this error:
```py
['Mon, May 30 2022 07:23PM', 'Successful']
Traceback (most recent call last):
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/BingRewards.py", line 172, in <module>
    main()
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/BingRewards.py", line 143, in main
    requests.post(discord, json=discord_content)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'Captain_Hook': No schema supplied. Perhaps you meant http://Captain_Hook?
```

**Comment by jhaugh0** [comment]
I think you may have just entered the wrong thing for the webhook, although what I typed up for help could probably use some more clarification. You'll need to copy the webhook URL from that page:
image


Then run
`python .\setup.py -d https://discord.com/api/webhooks/98097696519867...............`

then calling it at runtime with the -di and it'll show properly:
image

**Comment by jjjchens235** [comment]
Ok thanks that did the trick!

A few things:
- In `setup.py`, can we change the argument name from `--discord-webhook` to `--discord-webhook-url`
- When I run BingRewards.py `discord_webhook=False` yet the discord code block was still called.
	- Probably an issue with `if args.discord_webhook:` in BingRewards.py
- Please provide a small blurb in the **README**, something like:
	- Include it in this `Optional Reporting` [section](https://github.com/jjjchens235/bing-rewards/blob/master/README.md?plain=1#L19)
	- Include an `Discord Set-up Instructions` section that says something like:
		- Create a Discord channel if you don't have one
		- Within the channel, click `Server Settings`
		- Go to the `Integrations` tab
		- Create a webhook. The channel name does not matter, but copy down the webhook **URL**
		- Update your config file by running `python setup.py -d <your_webhook_url>`
		- When running `BingRewards.py` use the `-di` flag, i.e `python BingRewards.py -di`

**Comment by jhaugh0** [comment]
Nice catch on calling specifying false, forgot to test that one.

The rest is all updated now

**Comment by jjjchens235** [comment]
Thanks looks good.

**Comment by jjjchens235** [comment]
some future enhancements that I may make (notes for myself):

### Action items remaining someday
1. In [readme](https://github.com/jjjchens235/bing-rewards/blob/master/README.md?plain=1#L19), Include discord in the 'optional reporting' section
2. `BingRewards.py` needs to be linted
3. Consider refactoring discord into a separate class.
	1. Maybe discord and telegram should inherit from the same Base Reporting class. That way they can manipulate the following objects in the same way
		1.  rewards.stats object 
		2. hist_run_log
4. Consider changing the name of the arguments in this [code](https://github.com/jhaugh0/bing-rewards/blob/9dbaafc4be3280068a889de1350050f2f5bd4293/BingRewards/options.py#L260-L267) to `discord_reporting` or just `discord`. As this has nothing to do with webhook_url which setup.py handles separately.

**Comment by jjjchens235** [comment]
I have made the changes above https://github.com/jjjchens235/bing-rewards/commit/0d8a822f273d62347d139977ce802a27508b39f7

**Comment by icanotc** [comment]
Any plan to make the discord message an embed? I can implement it if time allows.

**Pull request merged**
