### PR TITLE
Add Stats.log

### PR DESCRIPTION
**Pull request by InTheDaylight14**
Hello, I have a small PR addressing https://github.com/jjjchens235/bing-rewards/issues/136. I've been looking for a way to keep closer track of my points so I took a shot at this. I'm no professional programmer so bear with me. 

This adds a stats log that is appended when __print_stats is called. It uses the existing array of stats that are collected at the end of the run. It outputs a semi-colon separated line with timestamp. This can be changed to comma separated, or separate lines. I wasn't sure what was best here. 

Example log file output from my testing: 
```
Mon, Feb 07 2022 11:57AM; Points earned: 568; Streak count: 25; 2 days until bonus gift; Available points: 29,043; Lifetime points: 29,043
Mon, Feb 07 2022 12:01PM; Points earned: 568; Streak count: 25; 2 days until bonus gift; Available points: 29,043; Lifetime points: 29,043
```

Let me know what I can improve on!

### CODE REVIEW

**Comment by InTheDaylight14** [comment]
This would be the incorrect one reported on my rewards. I didn't realize that number was wrong. Some logic could be added to calculate the point difference since last logged. That difference can be output in the summary too. 

There will be the occasional negative number when points are redeemed but that doesn't seem too bad.

**Comment by jjjchens235** [comment]
Thanks for the PR, I will try to take a look, there are 2 other PR's I need to finish integrating first FYI

From a quick glance, it looks good. The only thing I can think of is maybe putting the StatsLog on the BingRewards.py level, that's where all the different objects- including log objects- interact with each other. The rewards object would have the stats information as an instance variable and this variable can be passed into StatsLog. I'll have to think about it more.

Lastly, regarding the incorrect points, if you do decide to make any changes to that, please do so in a separate PR so that we can keep one feature per PR.

**Comment by jjjchens235** [comment]
A few things:

- Nice work, this was a simple and smart way of logging the stats
- I did indeed move the StatsLog to the `BingRewards.py` level.
- I converted the stats.log to `stats.json`. Am planning to move most/all the log files to json, so figured I may as well start with this new one.

Will move this over to dev branch and then on the next release to master. Thanks for the contribution!

**Comment by InTheDaylight14** [comment]
No problem! Thanks for the review.

**Pull request merged**
