### PR TITLE
Adds smaller integration for 2FA login - partially fixes #58

### LINKED ISSUE #58: 2FA Breaks the program
```
       >> Logging in
Traceback (most recent call last):
  File "D:\BingRewards\BingRewards\src\rewards.py", line 99, in __login
    WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.url_contains("https://account.microsoft.com/"))
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BingRewards\BingRewards\BingRewards.py", line 142, in <module>
    __main(args[0], arg1.replace("-", ""))
  File "D:\BingRewards\BingRewards\BingRewards.py", line 92, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "D:\BingRewards\BingRewards\src\rewards.py", line 907, in complete_all
    driver = self.__complete_edge_search()
  File "D:\BingRewards\BingRewards\src\rewards.py", line 752, in __complete_edge_search
    self.__login(driver)
  File "D:\BingRewards\BingRewards\src\rewards.py", line 105, in __login
    raise RuntimeError("Did NOT log in successfully")
RuntimeError: Did NOT log in successfully
```

### PR DESCRIPTION
**Pull request by revolutionisme**
> :exclamation: Partially fixes #58, only for 2FA enabled using Microsoft authenticator. 

Adds the ability to print the 2FA on the output log which then the user can select on their 2FA device. 
Default wait time has been added to be 30 seconds (or until the URL redirects after successfully entering the code)

The output would be as follows:
image

For the longer term, this code can be sent via telegram to the phone so that users can enter the correct code when crontab is activated and the user is not active on the machine.

### CODE REVIEW

**Comment by jjjchens235** [comment]
This is pretty nifty, nice job!

Minor issues that in combination cause the program to crash:
1. There's a naked `driver.find_element_by_id("loginHeader")`, causing the program to auto-fail if we get to this condition when it's not the 2FA page.
2. This doesn't handle the 'Approve Sign in Request' page with the following text: _Because you've turned on two-step verification, you need to approve request **** on your Microsoft Authenticator app._ Note that I only get to this page when I have cookies on. I'm guessing once I approve once, this will go away.


These issues should be pretty easy to fix on my side (unless you beat me to it) and I hope to merge to master soon.

**Comment by revolutionisme** [comment]
Aah, you are right. I will fix the first one and try to catch and throw or suppress the exception. The second one, unfortunately, I can't because I don't get that page to understand its structure!

**Comment by jjjchens235** [comment]
Hey, I made some small changes and have pushed to `dev` branch. I'll merge to master over the next few days, just wanted to make sure no unexpected bugs come up. Just a heads-up in case you wanted to take a look at the code changes and test it out for yourself.

**Comment by nootkroot** [comment]
I'm using 2FA and I'm not getting this message?

**Comment by jjjchens235** [comment]
Did you follow these instructions?

image

**Comment by nootkroot** [comment]
Also, instead of getting 3 different numbers to press I simply just get a yes or no sign in request. Am I doing something wrong?

**Pull request merged**
