### PR TITLE
fix: ensure stored_browser_data directory is always accessible - Closes #115

### LINKED ISSUE #115: Failed to create data directory
When executing BingRewards.py without options `-e` and `-p`, Chrome sends an error message : 
```
Failed to create data directory
Google Chrome cannot read and write to its data directory:
stored_browser_data
```
This message doesn't appear when launching command with `-e` and `-p` options.

image

### PR DESCRIPTION
**Pull request by ofelmy**
fix error reported in the issue 115 :
Failed to create data directory

Ensure user-data-dir argument will be passed with the directory full_path

### CODE REVIEW

**Comment by jjjchens235** [comment]
Could you give me an example of how this is different from what the current program does?


```sh
cd BingRewards/
rm -rf stored_browser_data
cd ~
# re-run from home directory, stored_browser_data is still being created within BingRewards/
python /Users/@myuser/Programming/Python/bing-rewards-master/BingRewards/BingRewards.py 
```

**Comment by ofelmy** [comment]
On Windows OS, the driver can't access to the stored_browser_data if the full path is not completed.
process to replay the error : 

```
PS D:\bing-rewards> Remove-Item .\BingRewards\stored_browser_data\ -Recurse -Force
PS D:\bing-rewards> python BingRewards/BingRewards.py -nhl

Command line options selected:
search_type=remaining, headless=False, email=None

['Tue, Nov 23 2021 09:31PM', 'Failed Web Search, Mobile Search, Offers']

        You selected remaining

> Starting Edge search

```
At this moment, a popup appears :
image

If I'm on the dev branch, the program continue tu run after closing the popup.
On the master branch, the program failed to continue with the following error message : 
```
Opening in existing browser session.
Traceback (most recent call last):
  File "D:\bing-rewards\BingRewards\BingRewards.py", line 164, in <module>
    __main()
  File "D:\bing-rewards\BingRewards\BingRewards.py", line 76, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "D:\bing-rewards\BingRewards\src\rewards.py", line 1266, in complete_all
    driver = self.__complete_edge_search()
  File "D:\bing-rewards\BingRewards\src\rewards.py", line 1064, in __complete_edge_search
    driver = Driver.get_driver(
  File "D:\bing-rewards\BingRewards\src\driver.py", line 135, in get_driver
    driver = webdriver.Chrome(path, options=options)
  File "C:\Users\ofelm\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 71, in __init__       
    RemoteWebDriver.__init__(
  File "C:\Users\ofelm\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 156, in __init__      
    self.start_session(capabilities, browser_profile)
  File "C:\Users\ofelm\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 251, in start_session 
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\ofelm\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute       
    self.error_handler.check_response(response)
  File "C:\Users\ofelm\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
```

Adding the current directory in the user-data-dir argument avoid this error

**Comment by jjjchens235** [comment]
Thank you, that makes sense! I'll merge in your PR over the next few days, will need to test it first.

**Comment by jjjchens235** [comment]
I ended up modifying your code slightly to point the full path to `drivers/` rather than `src/` as I think it makes more sense for the `stored_browser_data/` to live there. 

I'll merge to master soon. Thanks again for your help.

**Pull request merged**
