### PR TITLE
Add msedge support

### LINKED ISSUE #82: [Feature Request] Add Microsoft Edge driver option
Does this work in Microsoft Edge instead of chrome?

### PR DESCRIPTION
**Pull request by Summon528**
Fixes #82, **Only tested on Windows since I only have a Windows machine**

Due to the structure of msedgedriver's [website](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver), the code will try to download the latest stable version, latest beta version, latest dev version, latest canary version and then finally from the most recent version all the way to the oldest. This might or might not be a good thing but we can fix it later.

### CODE REVIEW

**Comment by jjjchens235** [comment]
Awesome! I have a `punch card` feature I want to get into dev/master this week, then I'll fix the merge conflicts and merge the PR.

**Comment by jjjchens235** [comment]
[Tested on mac] When running the code as is, I'm getting this error, regardless of which driver I specify.
```
Traceback (most recent call last):
  File "BingRewards/BingRewards.py", line 3, in <module>
    from src.driver import Driver
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/driver.py", line 222, in <module>
    class MsEdgeDriver(Driver):
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/driver.py", line 224, in MsEdgeDriver
    WebDriverOptions = webdriver.EdgeOptions
AttributeError: module 'selenium.webdriver' has no attribute 'EdgeOptions'
```

When I updated the code to this:
```
    from msedge.selenium_tools import EdgeOptions
    WebDriverOptions = EdgeOptions
```

I'm getting a new error only when I specify edge driver:
```
Traceback (most recent call last):
  File "BingRewards/BingRewards.py", line 3, in <module>
    from src.driver import Driver
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/driver.py", line 222, in <module>
    class MsEdgeDriver(Driver):
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/driver.py", line 224, in MsEdgeDriver
    WebDriverOptions = webdriver.EdgeOptions
AttributeError: module 'selenium.webdriver' has no attribute 'EdgeOptions'

**Comment by Summon528** [comment]
Try recreating a venv and ***not*** install `msedge-selenium-tools`?

**Comment by Summon528** [comment]
Oh, I am using selenium 4 and you are probably using 3.x? We could update the dependency or somehow update the code to work with selenium 3.x, the first solution will be way easier tho.

**Comment by jjjchens235** [comment]
Ah.. Selenium 4.0.  I will first have to upgrade Python versions lol, then will test this out.

I'm thinking that if the user encounters the AttributeError, instead of exiting the program, some sort of warning will appear saying they can't use the Edge driver until they upgrade.  I'm not sure if any of the other changes you made rely on 4.0 tho, so will have to test. Thoughts?

**Comment by Summon528** [comment]
I was thinking of a more selective error (exit when user select edge but run selenium 3 and run normally if using chrome). Lmk if you think your proposal is better, however I believe that implementation will cause the error message to be buried.

**Comment by jjjchens235** [comment]
Your solution is better.

**Comment by jjjchens235** [comment]
Finally got Selenium 4.0 and Edge works wonderfully now!
Will run a few more times and assuming no issues will merge to master this weekend. Great PR!

**Pull request merged**
