### PR TITLE
Fix 2FA with the approve sign in page

### PR DESCRIPTION
**Pull request by nootkroot**
This code is probably able to be cleaned up a bit but I think it looks fine so far.

### CODE REVIEW

**Comment by jjjchens235** [comment]
I get this error when running this normally:

```
BingRewards/ on branch nootkroot-master
(ins)$ python BingRewards.py -nhl

Command line options selected:
search_type=remaining, headless=False, email=None, cookies=False, telegram=True, driver=<class 'src.driver.ChromeDriver'>

['Sat, Mar 05 2022 06:01AM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected remaining
       >> Logging in
Traceback (most recent call last):
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/BingRewards.py", line 130, in <module>
    __main()
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1349, in complete_search_type
    init_points, driver = self.__get_available_points(driver=None, device_type=self.driver.WEB_DEVICE)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1238, in __get_available_points
    driver = self.__get_driver(device_type)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1227, in __get_driver
    self.__login(driver)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 161, in __login
    is_login_complete = self.__check_login_url(driver, driver.current_url)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 97, in __check_login_url
    driver.find_element(By.ID, "idChkBx_SAOTCAS_TD").click()
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 108, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 183, in _dispatch
    raise e
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 180, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="idChkBx_SAOTCAS_TD"]"}
  (Session info: chrome=98.0.4758.109)
Stacktrace:
0   chromedriver                        0x000000010e3d63c9 chromedriver + 5018569
1   chromedriver                        0x000000010e361333 chromedriver + 4539187
2   chromedriver                        0x000000010df36a88 chromedriver + 170632
3   chromedriver                        0x000000010df6b332 chromedriver + 385842
4   chromedriver                        0x000000010df6b4f1 chromedriver + 386289
5   chromedriver                        0x000000010df9d8b4 chromedriver + 592052
6   chromedriver                        0x000000010df8880d chromedriver + 505869
7   chromedriver                        0x000000010df9b604 chromedriver + 583172
8   chromedriver                        0x000000010df886d3 chromedriver + 505555
9   chromedriver                        0x000000010df5e95e chromedriver + 334174
10  chromedriver                        0x000000010df5f935 chromedriver + 338229
11  chromedriver                        0x000000010e3921ee chromedriver + 4739566
12  chromedriver                        0x000000010e3abf51 chromedriver + 4845393
13  chromedriver                        0x000000010e3b1928 chromedriver + 4868392
14  chromedriver                        0x000000010e3aca7a chromedriver + 4848250
15  chromedriver                        0x000000010e386c31 chromedriver + 4693041
16  chromedriver                        0x000000010e3c7978 chromedriver + 4958584
17  chromedriver                        0x000000010e3c7b01 chromedriver + 4958977
18  chromedriver                        0x000000010e3dd795 chromedriver + 5048213
19  libsystem_pthread.dylib             0x00007ff80622c4f4 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff80622800f thread_start + 15

```

The pertinent error is this
```
File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 97, in __check_login_url
    driver.find_element(By.ID, "idChkBx_SAOTCAS_TD").click()
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="idChkBx_SAOTCAS_TD"]"}
```

**Comment by jjjchens235** [comment]
Ok I think I know the issue. Can you update your code slightly to this:

```py
        elif "https://login.live.com/ppsecure" in url:
            # approve sign in page
            try:
                WebDriverWait(driver, .5).until(
                    EC.element_to_be_clickable((By.ID, 'idChkBx_SAOTCAS_TD'))
                ).click()
                self.__sys_out("Waiting for user to approve sign-in request. In Microsoft Authenticator, please select approve.", 2)

            except TimeoutException:
                pass

            #'stay signed in' page
            finally:
                WebDriverWait(driver, 30).until(
                    EC.element_to_be_clickable((By.ID, 'KmsiCheckboxField'))
                ).click()
                #yes, stay signed in
                driver.find_element(By.XPATH, '//*[@id="idSIButton9"]').click()
        #'agree to terms and conditions' page
```


Lastly please do the following:
1. Make sure the updated code still works for you
2. Rebase on top of remote `dev` branch
3. Squash into 1 commit

**Comment by nootkroot** [comment]
Worked great for me! I'll run the command now.

**Comment by nootkroot** [comment]
Seems like I did something wrong lol. Accidently pushed it to my master branch not realizing I needed to rebase and squash.

**Pull request merged**
