### PR TITLE
UK quiz functionality

### PR DESCRIPTION
**Pull request by chris987789**
Added check for cookie popups affecting the ability to complete polls and quizzes in the UK.

### CODE REVIEW

**Comment by connect-dots** [comment]
As per my earlier message I have now inserted the above commits into one of my builds and can confirm that this has indeed fixed the UK quiz issue. Great work! 

A couple of quizes did fail to initialise with 'could not detect overlay' (maybe timing out my end?), but enough were successful to raise the streak count upon completion (woohoo!). Either way, now that it is functional again, there's a decent chance that any outstanding quizes will stand a chance of completing during the week anyway. So from me it's a thumbs up! Thanks for providing this fix.

**Comment by chris987789** [comment]
> As per my earlier message I have now inserted the above commits into one of my builds and can confirm that this has indeed fixed the UK quiz issue. Great work!
> 
> A couple of quizes did fail to initialise with 'could not detect overlay' (maybe timing out my end?), but enough were successful to raise the streak count upon completion (woohoo!). Either way, now that it is functional again, there's a decent chance that any outstanding quizes will stand a chance of completing during the week anyway. So from me it's a thumbs up! Thanks for providing this fix.

The failed ones may not have actually failed, some come up as that when there are no questions but the checkmark still gets checked, if you re-run -o it should (hopefully) state <<Already Checked.

**Comment by connect-dots** [comment]
> The failed ones may not have actually failed, some come up as that when there are no questions but the checkmark still gets checked, if you re-run -o it should (hopefully) state <<Already Checked.

Yeah, you nailed it! Second run showed them as complete.
 Have double checked everything again, against a test account and it is working as expected on that as well. Lovely work.

**Comment by chris987789** [comment]
> > The failed ones may not have actually failed, some come up as that when there are no questions but the checkmark still gets checked, if you re-run -o it should (hopefully) state <<Already Checked.
> 
> Yeah, you nailed it! Second run showed them as complete.
> Have double checked everything again, against a test account and it is working as expected on that as well. Lovely work.

Enjoy your extra 2000+ points per month (daily and streak alone)

**Comment by chris987789** [comment]
@jjjchens235 I could have added a check for which market it's on and only added to the EN-GB market but with the single loop check now I figured it would be worth leaving in incase the EN-US site ever changes. 

Takes about 5 seconds longer on the searches and another 5 for the quizzes, 10 seconds overall but will save changing in the future and easier to update if anything changes than starting from scratch.

**Comment by jjjchens235** [comment]
@chris987789 
I was actually reviewing the code today prior to your new commit, and I had a similar thought.
I was going to ask you to add some market checking since it looked like the commits from 3 days ago would require cookie checking on EVERY unchecked offer.

However, with your most recent change, it looks like the check happens once for all searches, and once for all offers, which seems fine to me.

**Comment by chris987789** [comment]
gimme 5 mins I'll have a look

**Comment by chris987789** [comment]
> @chris987789
> Would it be possible to check for cookies prior to the first call to self.__sys_out_progress(current_progress, complete_progress, 3) ?
> This call happens in line 193 in your version of rewards.py
> 
> Right now, progress is being printed twice:
> >>> Progress: [ ] 0/100 (0%)
> >>> No cookie popup present
> >>> Progress: [######################## ] 80/100 (80%)
> 
> All good if not possible.

Possibly but will have to check tomorrow, may be able to introduce it after the driver.get(self.__BING_URL) but have to check loading times, if it processes back onto the current progress page too fast then may miss the popup resulting in search fails due to timeouts.

I'll let you know tomorrow when my search has re-cycled.

**Comment by chris987789** [comment]
> @chris987789
> Would it be possible to check for cookies prior to the first call to self.__sys_out_progress(current_progress, complete_progress, 3) ?
> This call happens in line 193 in your version of rewards.py
> 
> Right now, progress is being printed twice:
> >>> Progress: [ ] 0/100 (0%)
> >>> No cookie popup present
> >>> Progress: [######################## ] 80/100 (80%)
> 
> All good if not possible.

Not had time to change and check this and I'm back to work tomorrow so I'd recommend just updating as is, I'm sure one extra line in the output shouldn't be a major issue to anyone.

**Pull request merged**
