### PR TITLE
New Notification System

### PR DESCRIPTION
**Pull request by hosein-hub**
i have added 2 new notification delivery system
1 desktop notification
2 notify.run notifications

can i add a link or wallet address for donation in readme.md for my self?
I can also develop this program with you ?

### CODE REVIEW

**Comment by jjjchens235** [comment]
This is a lot of code, but I'm not sure what the purpose of this is? Why does the user need desktop notifications?

**Comment by ForceConstant** [comment]
> This is a lot of code, but I'm not sure what the purpose of this is? Why does the user need desktop notifications?

Specially if using something like telegram, couldn't you just get telegram notifications on your desktop?

**Comment by hosein-hub** [comment]
For example, I have scheduled the program and many times I do not open Telegram, but my system is open and I am working.  This helps me understand at what stage the program is and may not work for everyone, but it's good for me.  I would also like to work on the gui a bit and maybe maybe develop a desktop application for it.
If you have ideas i can work on it ❤️
thanks for your time and please answer my question 
And one more help
Can anyone help me for claiming my reward? 
After clicking claim bing says enter number and after this bing says have a problem with my number
Im not on any country bing accepted , i have a virtual number (google voice) but bing dos not support my number.

**Comment by jjjchens235** [comment]
Hosein- I can tell you put a TON of work into this, but I think the command line output already does a good job in alerting the user what their progress is. If I'm missing something, please let me know.

Regarding redeeming your reward, as you already surmised, you need an actual US phone number.

Lastly, there are a ton of features that I need help with, if you're interested, I can list the features in more detail.

**Comment by hosein-hub** [comment]
Thanks for reply.
Offshore list the details and features and we can work together. Need my email or some social media id?

**Comment by jjjchens235** [comment]
I updated the issues page with `help wanted` tags so that everyone can collaborate together. Thanks again for your help!

**Pull request closed without merging**
