### PR TITLE
restore raspberry pi compatibility 

### PR DESCRIPTION
**Pull request by alecm858**

### CODE REVIEW

**Comment by ForceConstant** [comment]
Just wondering if everything is ok with this PR. You had 26 commits, but the diff only shows like 3 lines different from master. Is this expected?

**Review by jjjchens235 — COMMENTED** [review]
can you please update this to an `f string`? I've been trying to move the print statements to that format.

**Comment by jjjchens235** [comment]
i'll manually add this update

**Comment by jjjchens235** [comment]
resolved by bbf56a4

**Pull request closed without merging**
