### PR TITLE
Add Docker Feature

### PR DESCRIPTION
**Pull request by Killerherts**
Added the docker build file.
Changed the driver to let the container write to disk so chrome does not crash.
Moved setup.py to the main BingRewards folder to allow password to be setup inside of container
cron was added to the Dockerfile for scheduling support inside container

docker pull killerherts/bing-rewards:latest

docker exec -it bing-rewards /bin/bash
then 
python setup.py
...
...

still to do
update read me for reflect container run instructions
create docker-compose file

### CODE REVIEW

**Comment by jjjchens235** [comment]
Hey I read your original comment and you mentioned that it would be ideal for the user not to need python installed locally. Is that not a concern any more?

**Comment by ForceConstant** [comment]
It would be great if this had an embedded x desktop so you could run on headless server. Maybe using something like novnc

**Comment by Killerherts** [comment]
@jjjchens235 No with setup.py moved into BingRewards I was able to roll it up with the rest of the image. Users can simply run setup.py from within the docker container. I did not bother with passable args since users can just include their old config folder directly with a volume mount. 

@ForceConstant this runs on headless servers you just need to use -nsb. I am running the container on my Unraid server through docker compose. I am emulating a monitor in the build file. I can probably add a template to the Unraid community store for people who don't run docker if there is actually demand

**Comment by belgio99** [comment]
Could you guys take a look at my Dockerfile (in my fork)? Currently has no cron support, and I forked the main repo a while ago so now that the main project went on I can't automatically sync new commits. Since my bing-rewards runs on a Raspberry Pi, I tried to optimize the image as much as possible. While @Killerherts image is 1.62GB, mine is about 400MB (and maybe it can be optimized further using multi-stage builds).
In my docker run, I use a docker volume (bing-rewards-data) to store config.py, so even if the container stops, the configs are preserved (check docker-init.sh).
Last thing, I put the ENV variable AM_I_IN_A_DOCKER_CONTAINER since even if raspberry is armv7, alpine apk installs chromedriver in another folder (check my commits to driver.py).

**Comment by Killerherts** [comment]
> Could you guys take a look at my Dockerfile (in my fork)? Currently has no cron support, and I forked the main repo a while ago so now that the main project went on I can't automatically sync new commits. Since my bing-rewards runs on a Raspberry Pi, I tried to optimize the image as much as possible. While @Killerherts image is 1.62GB, mine is about 400MB (and maybe it can be optimized further using multi-stage builds). In my docker run, I use a docker volume (bing-rewards-data) to store config.py, so even if the container stops, the configs are preserved (check docker-init.sh). Last thing, I put the ENV variable AM_I_IN_A_DOCKER_CONTAINER since even if raspberry is armv7, alpine apk installs chromedriver in another folder (check my commits to driver.py).

I have never used chromium for this script even outside of docker as the internal auto-download for chrome driver is all based on chrome-stable. I am not sure about your cron but I would look at this on thier wiki as it looks like it has a unique setup I'm not familiar with it though sorry. https://wiki.alpinelinux.org/wiki/Alpine_Linux:FAQ#:~:text=apk%20upgrade%20%2D%2Davailable-,Why%20don%27t%20my%20cron%20jobs%20run%3F,myscript%20will%20run%2C%20but%20/etc/periodic/daily/myscript.sh%20won%27t.,-Time%20and%20timezones

My suggestion would be just to keep your config folder and just pull my image down again I can look into reducing it size by adding no-cache, using python-slim, and doing a cleanup on apt after the install. But I don't think you're going to have a ton of luck with chromium without doing modification to the script and I doubt many would be in favor of this.

**Comment by belgio99** [comment]
Thanks! I went with Chromium since there is no Chrome for Raspberry Pi (mine is armv7), so currently I just can't run your image. About Chromium, I am already running bing-rewards on bare metal with chromium-chromedriver and cron, and it's working perfectly. In fact, I think that in driver.py, if the chromedriver path is correctly set, I don't think that there's much difference between Chrome and Chromium, but I would be happy to know if I'm wrong (maybe @jjjchens235 can help us on this).

**Comment by Killerherts** [comment]
I played with it a bit but I am not an expert so honestly only got little shaved off 
```FROM python:3.9.5


COPY /BingRewards /BingRewards
WORKDIR /BingRewards

# install google chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
	sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' && \
	apt-get -y update --no-install-recommends  && \
	apt-get install -y google-chrome-stable --no-install-recommends  && \
	apt-get install -y cron && apt-get install -y nano && \
	apt-get autoremove -y && apt-get clean
	
# Set display port as an environment variable
ENV DISPLAY=:99

RUN pip install --upgrade pip && pip install -r requirements.txt && \
	touch /var/log/cron.log && \
	(crontab -l 2>/dev/null; echo "* */8 * * * export DISPLAY=0 && /usr/local/bin/python /BingRewards/BingRewards.py -nsb") | crontab -
# Run the command on container startup
CMD /etc/init.d/cron start && tail -f /var/log/cron.log
```
Switching to chromium would save like 80mb i looked it up. dive shows there are 2 large layers so I'll work on it some more. I see your point on the arm thing though. Ill look at it some more message me is discord if you want Killerherts#5979

**Comment by Killerherts** [comment]
@belgio99 I have rebuilt the docker using chromium and it was 1.08gb instead of 1.06gb. I now have 2 image tags up one is killerherts/bing-rewards:latest with the traditional google-chrome-stable
killerherts/bing-rewards:chromium is with chromium (I breifly test this and cron works as well as the script but I have not ran it for multple days or anything) I hope this helps out with your PI situation cheers

**Comment by belgio99** [comment]
That's awesome! Thank you so much. I'll try it in the next few days. Still, it would be extremely useful to build an alpine image, for maximum space saving (about 60% less space than python:slim). I'm working on that.
Furthermore, the optimal Docker goal would be that the images (especially the :latest one) would be platform-independent (the main purpose of containers: run anywhere with no hassle), so maybe we might consider switching the :latest tag to the chromium image, and keep the google-chrome-stable as a separate image with its own tag?

**Comment by Killerherts** [comment]
Once tested I would have no problem moving it to the latest I just haven't tested it so I wanted to keep my og image up cuz I don't wanna run the bleeding edge on my main account. So far I have not seen any differences or issues. I will look into alpine in a bit and see how much more size I can shave.

**Comment by belgio99** [comment]
I just updated my fork, my Dockerfile is Alpine based. I have it working, but I still have to implement the cron functionality. Currently the container quits when the job is done.
If you want to contribute, feel free to do it!
The final image size on my computer is 531.75 MB, so about a 50% cut from your python:slim base image.

**Comment by Killerherts** [comment]
@belgio99  because of several things that change when you use alpine I am pretty firmly against switching the main branch to alpine. I feel it should run like most main stream distributions; I am actually going to update my PR so only the 2 line changes are needed in drivers.py.

**Comment by Killerherts** [comment]
I am going to rework this so it does not move setup.py only making the additional line change to driver.py.

**Pull request closed without merging**
