### PR TITLE
added telegram bot notifications

### PR DESCRIPTION
**Pull request by hosein-hub**
added simple telegram bot notification

### CODE REVIEW

**Comment by jjjchens235** [comment]
This is good stuff. 

FYI, I'm going to add base64 encode logic to setup.py so you'll have to `re-run setup.py` if you want to use master version in the future.

There are quite a few changes so I'm going to take my time testing this over next week or 2.

**Comment by hosein-hub** [comment]
thanks man <3
have a good week in testing
i will try to add some new stuff to your script for better working

**Comment by DimaRazb** [comment]
Awesome, thanks for this option, much appreciated, man!
Would be great if you update the Readme file for the telegram options -t and -nt.
Went to the code to grab it when I saw telegram=true on my updated run.

Cheers!

**Comment by ForceConstant** [comment]
Great PR: It would be good also if any errors were reported via telegram bot also.

**Comment by hosein-hub** [comment]
i will try to add error reporting to telegram notification
also i will try to add slack , discord and email reporting :)

**Comment by jjjchens235** [comment]
Hey Hosein-hub, I've never used telegram before, so excuse my ignorance. 
The set-up file asks for these two items:
```py
telegrambotkey = encode_input(input("*Telegram Bot Key (optional, press enter to skip): "))
telegramuserid = encode_input(input("*Telegram User ID (optional, press enter to skip): "))
```

For the bot key, I tried both the channel name, ie '@blahblahbot' and the bot token that was generated upon bot creation.
For telegram UserId, I used the useridbot to obtain the userid.

However, when running this program- using the 2 different bot keys- the response I'm getting is a 404 error, the response is returned from this code:
```py
                resp = requests.get(reply_url)

```

What am I doing wrong?

**Comment by jjjchens235** [comment]
My bad, the bot token I was entering was wrong

**Comment by jjjchens235** [comment]
I've made some slight modifications to the telegram feature, the changes are in dev if you want to take a look. 
If there aren't any objections, I'll merge with master in the upcoming day(s).

**Pull request merged**
